export enum ComponentName {
  ManageLookupsComponent = "ManageLookupsComponent",
  DefinitionStagesComponent = "DefinitionStagesComponent",
  ListSettingsComponent = "ListSettingsComponent",
  ApplicationDetailComponent = "ApplicationDetailComponent",
  ApplicationDetailDialogComponent = "ApplicationDetailDialogComponent",
  CustomFieldsFormComponent = "CustomFieldsFormComponent",
  RequestDetailsComponent = "RequestDetailsComponent",
  SubmitRequestComponent = "SubmitRequestComponent",
  SubmitRequestV2Component = "SubmitRequestV2Component",
  AddApplicantRequestDialogComponent = "AddApplicantRequestDialogComponent",
  SidenavbarComponent = "SidenavbarComponent",
  LookupItemsListComponent = "LookupItemsListComponent",
  ListApplicantsComponent = "ListApplicantsComponent",
  AddApplicantRequestInpageComponent = "AddApplicantRequestInpageComponent",
  ProfileTemplateDetailsComponent = "ProfileTemplateDetailsComponent",
  ApplicantRequestAuthenticationComponent = "ApplicantRequestAuthenticationComponent",
  SubmitApplicantRequestComponent = "SubmitApplicantRequestComponent",
  LookupTabsComponent = "LookupTabsComponent",
  LinkApplication = "LinkApplication",
  ApplicantRequestDetailsComponent = "ApplicantRequestDetailsComponent",
  ApplicationStagesDetailsComponent = "ApplicationStagesDetailsComponent",
  SubmissionRequestComponent = "SubmissionRequestComponent",
  ApplicationDialog = "ApplicationDialog"
}
