export class OppProActivity {
  constructor() {}
  id: number;
  appType?:number;
  effortSum?:any;
  effortInHour?:any;
  effortInMinute?:any;
  channel?:any;
  progressStatus?:any;
  progressStatusColor?:any;
  canEdit?:any;
  title: string;
  description: string;
  note: string;
  callFromName?: string;
  callFromId?: string;
  activityId: number;
  activityType: string;
  actualClosingDate: string;
  actualDurationMinutes: string;
  actualDurationMinutesFormatted: string;
  amISubscriber: boolean;
  associatedEntityId: number;
  associatedEntityName: string;
  associatedEntityTitle: string;
  attachments: any;
  callDirection: number;
  callToActionId: number;
  callToActionTitle: string;
  callToId: number;
  callToName: string;
  completedOnDate: string;
  createdById: number;
  createdByName: string;
  createdDate: string;
  durationMinutes: string;
  durationMinutesFormatted: null;
  hasAttachment: boolean;
  isCancelled: boolean;
  isCompleted: boolean;
  meetingIsAllDayEvent: any;
  organizationId: number;
  organizationName: string;
  ownerId: number;
  ownerName: string;
  priorityCode: number;
  reminderAddedDate: string;
  reminderSelectedDate: string;
  reminderSelectedOption: string;
  scheduleEnd: string;
  scheduleStart: string;
  subject: string;
  updatedById: number;
  updatedByName: string;
  startTime: any;
  endTime: any;
  date: any;
  callToNameObj: any;
}
